# Generated by Django 4.2.13 on 2024-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0002_alter_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
