# Generated by Django 4.2.13 on 2024-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0003_book_daily_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("H", "Hard"), ("S", "Soft")], max_length=100
            ),
        ),
    ]
