# Generated by Django 4.2.13 on 2024-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pn", "Pending"), ("Pd", "Paid")], max_length=2
            ),
        ),
    ]
