# Generated by Django 4.2.13 on 2024-07-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowings",
            options={"verbose_name_plural": "Borrowings"},
        ),
        migrations.AlterField(
            model_name="borrowings",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pd", "Paid"), ("Pn", "Pending")], max_length=2
            ),
        ),
    ]
