# Generated by Django 4.2.13 on 2024-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0003_alter_borrowings_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="money_to_pay",
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pn", "Pending"), ("Pd", "Paid")], max_length=2
            ),
        ),
    ]
