# Generated by Django 4.2.13 on 2024-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0004_remove_payment_money_to_pay_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("Payment", "PAYMENT"), ("Fine", "FINE")], max_length=10
            ),
        ),
    ]
