# Generated by Django 4.2.13 on 2024-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0005_alter_payment_status_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.TextField(),
        ),
    ]
