# Generated by Django 4.2.13 on 2024-07-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0006_alter_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True),
        ),
    ]
