# Generated by Django 4.2.13 on 2024-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowings_service",
            "0007_alter_payment_session_id_alter_payment_session_url",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("Payment", "PAYMENT"), ("Fine", "FINE")],
                default="Payment",
                max_length=10,
            ),
        ),
    ]
