# Generated by Django 4.2.13 on 2024-07-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowings_service",
            "0008_alter_borrowings_borrow_date_alter_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="borrow_date",
            field=models.DateField(),
        ),
    ]
